AllenNeuralDynamics/aind-data-access-api

src/aind_data_access_api/document_store.py
tests/test_document_store.py
tests/test_secrets_access.py

Closes #18
- Adds option to set retryWrites in the MongoClient to False
- Runs linters

feat: adds retryWrites arg

---

src/aind_data_access_api/document_db.py
tests/test_document_db.py

- hot fix to converts json string to json obj when upserting docs through the api

fix: updates docdb record upsert

---

pyproject.toml
src/aind_data_access_api/rds_tables.py
tests/test_rds_tables.py

Closes #23
- Can mostly use old rds api
- Needed to downgrade to SQLAlchemy==1.4.49 to get things to work
- Needed to set index=False since Redshift doesn't support indexing
- Used method='multi' for pandas method instead of custom method. This will be slower for writing large tables, but hopefully quick enough.

feat: updates rds api to handle redshift

---

src/aind_data_access_api/document_db.py
tests/test_document_db.py

- hot fix to serialize json properly to be able to write to the docdb

hot-fix: docdb json serializer

---

src/aind_data_access_api/rds_tables.py

Including an optional string to connect to a specific database with a specific driver. This solves writing a super data type to a redshift database.

adding optional drivername to the connection url

---

pyproject.toml
src/aind_data_access_api/document_db.py
tests/test_document_db.py

Closes #37 
- Adds method to delete one record from docdb
- Adds method to delete many records from docdb
- Adds convenient wrapper to MetadataClient
- Updates to min python version to 3.8
- Stores Session object as cached property
- Updates unit tests

feat: adds delete method to api

---

pyproject.toml
src/aind_data_access_api/credentials.py
src/aind_data_access_api/rds_tables.py
tests/test_rds_tables.py

closes #39 
Pandas 2.2 and onwards no longer support SQLAlchemy 1.4. This PR puts a maximum limit on Pandas for now. Also adds a validator for db name so that database=dbname

Fix: upgrade SqlAlchemy for compatibility issues

---

README.md
docs/source/ExamplesDocDBDirectConnection.rst
docs/source/UserGuide.rst
docs/source/aind_data_access_api.rst
docs/source/index.rst

closes #49 
Readthedocs updates:
- Move Usage docs (for DocDBSSH and RDS clients) from readme to User Guide page
- Add usage docs for the REST API client and Mongo Compass
- Add `DocumentDbSSHClient` examples (show examples w/o projections first)
- Enable automodule for `aind_data_access_api.utils` docs
A future ticket will address adding Contributing.rst; once done, remaining sections of the README can be removed.

docs: add docdb interface and utils usage to readthedocs

---

README.md
docs/source/ExamplesDocDBDirectConnection.rst
docs/source/UserGuide.rst
docs/source/aind_data_access_api.rst
docs/source/index.rst
src/aind_data_access_api/__init__.py
src/aind_data_access_api/utils.py
tests/resources/utils/example_metadata.nd.json
tests/resources/utils/example_metadata1.nd.json
tests/resources/utils/example_metadata2.nd.json
tests/test_utils.py

Release v0.11.0
- adds utils module
- adds User Guide to readthedocs

Release v0.11.0

---

docs/source/UserGuide.rst
src/aind_data_access_api/document_db.py
src/aind_data_access_api/document_db_ssh.py
src/aind_data_access_api/document_store.py
src/aind_data_access_api/models.py
tests/test_document_db.py

closes #61 
`MetadataDbClient` for rest api:
- added retrieve and upsert methods that read/write raw records to docdb
- added deprecation warnings for methods that use `DataAssetRecord`
- updated User Guide example

feat: do not convert docdb records to DataAssetRecord

---

docs/source/UserGuide.rst
src/aind_data_access_api/document_db.py
tests/test_document_db.py

closes #75 
- add new `use_signed_requests` option to enforce signed requests when using read_write api
- update `max_payload_size` to 5MB for bulk writes

feat: update docdb rest api client for readwrite

---

docs/source/ExamplesDocDBDirectConnection.rst
docs/source/ExamplesDocDBRestApi.rst
docs/source/index.rst
src/aind_data_access_api/document_db.py
tests/test_document_db.py

closes #78
- Add `aggregate_docdb_records()` in `aind_data_access_api.document_db.MetadataDbClient`
- Add examples to readthedocs for docdb rest api to match ssh client examples

feat: support aggregations in docdb rest api

---

pyproject.toml
src/aind_data_access_api/helpers/data_schema.py
src/aind_data_access_api/helpers/docdb.py
tests/test_helpers_data_schema.py
tests/test_helpers_docdb.py

closes #103
Updates/adds `get_id_from_name` and `get_name_from_id` helper methods that raise ValueError for failed record searches. Only `get_id_from_name` prints warnings for multiple records since ids are unique.

feat: get_id_from_name and get_name_from_id helpers

---

README.md
docs/source/UserGuide.rst

Adds instructions to the `README.md` and to `docs.UserGuide.rst` to explain how to install the package with/without optional dependencies.
Solves issue #120

Feat: Update docs to include install instructions

---

docs/source/ExamplesDocDBRestApi.rst
pyproject.toml
src/aind_data_access_api/document_db.py
tests/test_document_db.py
tests/test_helpers_docdb.py

Closes #6
Closes #108 
- Allows user to pass in requests.Session object
- Uses raise_for_status for requests exceptions (This will introduce a breaking change if users added error handlers in their code)
- Updates some urls in tests to be example.com
- Adds lower bound to aind-data-schema
- Changes cached_property to property
- Updates internal property names
- Moves boto3 to core requirement since it's required to use the docdb write methods

BREAKING CHANGE: uses raise_for_status for requests

---

docs/source/ExamplesDocDBDirectConnection.rst
docs/source/ExamplesDocDBRestApi.rst
src/aind_data_access_api/document_db.py
src/aind_data_access_api/utils.py
tests/test_document_db.py

closes #125 
closes #104 
A new insert endpoint is being added to the DocDB REST API at `/v1/{database}/{collection}/insert_one`.
This PR adds support for writing fieldnames with special chars:
- adds `insert_one_docdb_record` in `MetadataDbClient`
- remove `is_dict_corrupt` checks. This also enables updates to nested fields as requested by #104
- update docs

feat: support insert_one and updates to nested fields

---

src/aind_data_access_api/document_db.py
src/aind_data_access_api/utils.py
tests/test_document_db.py
tests/test_utils.py

fixes https://github.com/AllenNeuralDynamics/aind-lambda-functions/issues/146
This PR updates `MetadataDbClient` so that we do not drop large batches:
- `_find_records`: sends requests to new /find endpoint which fetches "dynamic" batches of records
- `retrieve_docdb_records`: paginates docdb using new /find endpoint until there are no more records or the limit is reached
Please note that "paginate" parameters were marked as deprecated. Users can still provide them, but they are not used.

fix: do not drop large record batches

---

docs/source/index.rst

PR adds a link back from the documentation to the github code on the frontpage. (Requested by Tom for all sci comp RTD repos)

docs: add link back to github

---

src/aind_data_access_api/document_db.py
tests/test_document_db.py

related to https://github.com/AllenNeuralDynamics/aind-aws-infrastructure/issues/331

feat: remove _id check for inserts

---

docs/source/ExamplesDocDBRestApi.rst
src/aind_data_access_api/document_db.py
tests/test_document_db.py

Closes #149. Moved method into Client class instead of MetadataDbClient, per ticket update. Added corresponding unit tests and updated docs.

refactor: move fetch_records_by_filter_list into Client class

---

src/aind_data_access_api/document_db.py
tests/test_document_db.py

closes #170
Adds method to sign and send DELETE request to new asset de-registration endpoint: `/v1/assets/deregister`
Usage:
```py
response = docdb_client.deregister_asset(s3_location=s3_location)
```

feat: MetadataDbClient.deregister_asset method
